#ifndef ANTDEFINES_H
#define ANTDEFINES_H 
#include <stdint.h>
#define ANT_CLOCK_FREQUENCY ((uint32_t)32768)
#define ANT_STANDARD_DATA_PAYLOAD_SIZE ((uint8_t)8)
#define RADIO_TX_POWER_LVL_CUSTOM ((uint8_t)0x80)
#define RADIO_TX_POWER_LVL_0 ((uint8_t)0x00)
#define RADIO_TX_POWER_LVL_1 ((uint8_t)0x01)
#define RADIO_TX_POWER_LVL_2 ((uint8_t)0x02)
#define RADIO_TX_POWER_LVL_3 ((uint8_t)0x03)
#define RADIO_TX_POWER_LVL_4 ((uint8_t)0x04)
#define PROXIMITY_THRESHOLD_CUSTOM ((uint8_t)0x80)
#define PROXIMITY_THRESHOLD_OFF ((uint8_t)0x00)
#define PROXIMITY_THRESHOLD_1 ((uint8_t)0x01)
#define PROXIMITY_THRESHOLD_2 ((uint8_t)0x02)
#define PROXIMITY_THRESHOLD_3 ((uint8_t)0x03)
#define PROXIMITY_THRESHOLD_4 ((uint8_t)0x04)
#define PROXIMITY_THRESHOLD_5 ((uint8_t)0x05)
#define PROXIMITY_THRESHOLD_6 ((uint8_t)0x06)
#define PROXIMITY_THRESHOLD_7 ((uint8_t)0x07)
#define PROXIMITY_THRESHOLD_8 ((uint8_t)0x08)
#define PROXIMITY_THRESHOLD_9 ((uint8_t)0x09)
#define PROXIMITY_THRESHOLD_10 ((uint8_t)0x0A)
#define PARAMETER_RX_NOT_TX ((uint8_t)0x00)
#define PARAMETER_TX_NOT_RX ((uint8_t)0x10)
#define PARAMETER_SHARED_CHANNEL ((uint8_t)0x20)
#define PARAMETER_NO_TX_GUARD_BAND ((uint8_t)0x40)
#define PARAMETER_RX_ONLY ((uint8_t)0x40)
#define EXT_PARAM_ALWAYS_SEARCH ((uint8_t)0x01)
#define EXT_PARAM_IGNORE_TRANSMISSION_TYPE ((uint8_t)0x02)
#define EXT_PARAM_FREQUENCY_AGILITY ((uint8_t)0x04)
#define EXT_PARAM_AUTO_SHARED_SLAVE ((uint8_t)0x08)
#define EXT_PARAM_FAST_INITIATION_MODE ((uint8_t)0x10)
#define EXT_PARAM_ASYNC_TX_MODE ((uint8_t)0x20)
#define CHANNEL_TYPE_SLAVE ((uint8_t) 0x00)
#define CHANNEL_TYPE_MASTER ((uint8_t) 0x10)
#define CHANNEL_TYPE_SLAVE_RX_ONLY ((uint8_t) 0x40)
#define CHANNEL_TYPE_MASTER_TX_ONLY ((uint8_t) 0x50)
#define CHANNEL_TYPE_SHARED_SLAVE ((uint8_t) 0x20)
#define CHANNEL_TYPE_SHARED_MASTER ((uint8_t) 0x30)
#define ANT_ID_SIZE ((uint8_t)4)
#define ANT_ID_TRANS_TYPE_OFFSET ((uint8_t)3)
#define ANT_ID_DEVICE_TYPE_OFFSET ((uint8_t)2)
#define ANT_ID_DEVICE_NUMBER_HIGH_OFFSET ((uint8_t)1)
#define ANT_ID_DEVICE_NUMBER_LOW_OFFSET ((uint8_t)0)
#define ANT_ID_DEVICE_TYPE_PAIRING_FLAG ((uint8_t)0x80)
#define ANT_TRANS_TYPE_SHARED_ADDR_MASK ((uint8_t)0x03)
#define ANT_TRANS_TYPE_1_BYTE_SHARED_ADDRESS ((uint8_t)0x02)
#define ANT_TRANS_TYPE_2_BYTE_SHARED_ADDRESS ((uint8_t)0x03)
#define STATUS_CHANNEL_STATE_MASK ((uint8_t)0x03)
#define STATUS_UNASSIGNED_CHANNEL ((uint8_t)0x00)
#define STATUS_ASSIGNED_CHANNEL ((uint8_t)0x01)
#define STATUS_SEARCHING_CHANNEL ((uint8_t)0x02)
#define STATUS_TRACKING_CHANNEL ((uint8_t)0x03)
#define CAPABILITIES_NO_RX_CHANNELS ((uint8_t)0x01)
#define CAPABILITIES_NO_TX_CHANNELS ((uint8_t)0x02)
#define CAPABILITIES_NO_RX_MESSAGES ((uint8_t)0x04)
#define CAPABILITIES_NO_TX_MESSAGES ((uint8_t)0x08)
#define CAPABILITIES_NO_ACKD_MESSAGES ((uint8_t)0x10)
#define CAPABILITIES_NO_BURST_TRANSFER ((uint8_t)0x20)
#define CAPABILITIES_NETWORK_ENABLED ((uint8_t)0x02)
#define CAPABILITIES_SERIAL_NUMBER_ENABLED ((uint8_t)0x08)
#define CAPABILITIES_PER_CHANNEL_TX_POWER_ENABLED ((uint8_t)0x10)
#define CAPABILITIES_LOW_PRIORITY_SEARCH_ENABLED ((uint8_t)0x20)
#define CAPABILITIES_SCRIPT_ENABLED ((uint8_t)0x40)
#define CAPABILITIES_SEARCH_LIST_ENABLED ((uint8_t)0x80)
#define CAPABILITIES_LED_ENABLED ((uint8_t)0x01)
#define CAPABILITIES_EXT_MESSAGE_ENABLED ((uint8_t)0x02)
#define CAPABILITIES_SCAN_MODE_ENABLED ((uint8_t)0x04)
#define CAPABILITIES_RESERVED ((uint8_t)0x08)
#define CAPABILITIES_PROX_SEARCH_ENABLED ((uint8_t)0x10)
#define CAPABILITIES_EXT_ASSIGN_ENABLED ((uint8_t)0x20)
#define CAPABILITIES_FS_ANTFS_ENABLED ((uint8_t)0x40)
#define CAPABILITIES_FIT1_ENABLED ((uint8_t)0x80)
#define CAPABILITIES_ADVANCED_BURST_ENABLED ((uint8_t)0x01)
#define CAPABILITIES_EVENT_BUFFERING_ENABLED ((uint8_t)0x02)
#define CAPABILITIES_EVENT_FILTERING_ENABLED ((uint8_t)0x04)
#define CAPABILITIES_HIGH_DUTY_SEARCH_MODE_ENABLED ((uint8_t)0x08)
#define CAPABILITIES_ACTIVE_SEARCH_SHARING_MODE_ENABLED ((uint8_t)0x10)
#define CAPABILITIES_RADIO_COEX_CONFIG_ENABLED ((uint8_t)0x20)
#define CAPABILITIES_SELECTIVE_DATA_UPDATE_ENABLED ((uint8_t)0x40)
#define CAPABILITIES_ENCRYPTED_CHANNEL_ENABLED ((uint8_t)0x80)
#define CAPABILITIES_RFACTIVE_NOTIFICATION_ENABLED ((uint8_t)0x01)
#define CHANNEL_NUMBER_MASK ((uint8_t)0x1F)
#define SEQUENCE_NUMBER_MASK ((uint8_t)0xE0)
#define SEQUENCE_NUMBER_ROLLOVER ((uint8_t)0x60)
#define SEQUENCE_FIRST_MESSAGE ((uint8_t)0x00)
#define SEQUENCE_LAST_MESSAGE ((uint8_t)0x80)
#define SEQUENCE_NUMBER_INC ((uint8_t)0x20)
#define BURST_SEGMENT_CONTINUE ((uint8_t)0x00)
#define BURST_SEGMENT_START ((uint8_t)0x01)
#define BURST_SEGMENT_END ((uint8_t)0x02)
#define ANT_LIB_CONFIG_MASK_ALL ((uint8_t)0xFF)
#define ANT_LIB_CONFIG_RADIO_CONFIG_ALWAYS ((uint8_t)0x01)
#define ANT_LIB_CONFIG_MESG_OUT_INC_TIME_STAMP ((uint8_t)0x20)
#define ANT_LIB_CONFIG_MESG_OUT_INC_RSSI ((uint8_t)0x40)
#define ANT_LIB_CONFIG_MESG_OUT_INC_DEVICE_ID ((uint8_t)0x80)
#define ANT_EXT_MESG_BITFIELD_DEVICE_ID ((uint8_t)0x80)
#define ANT_EXT_MESG_BITFIELD_RSSI ((uint8_t)0x40)
#define ANT_EXT_MESG_BITFIELD_TIME_STAMP ((uint8_t)0x20)
#define ANT_EXT_MESG_BIFIELD_EXTENSION ((uint8_t)0x01)
#define RSSI_TYPE_AGC_EXT_MESG_FIELD_SIZE ((uint8_t)4)
#define RSSI_TYPE_DBM_EXT_MESG_FIELD_SIZE ((uint8_t)3)
#define RSSI_TYPE_OFFSET ((uint8_t)0)
#define RSSI_AGC_TYPE ((uint8_t)0x10)
#define RSSI_DBM_TYPE ((uint8_t)0x20)
#define RSSI_TYPE_AGC_THRESHOLD_OFFSET ((uint8_t)1)
#define RSSI_TYPE_AGC_REGISTER_LOW ((uint8_t)2)
#define RSSI_TYPE_AGC_REGISTER_HIGH ((uint8_t)3)
#define RSSI_TYPE_DBM_VALUE ((uint8_t)1)
#define RSSI_TYPE_DBM_SETTING ((uint8_t)2)
#define RESET_FLAGS_MASK ((uint8_t)0xE0)
#define RESET_SUSPEND ((uint8_t)0x80)
#define RESET_SYNC ((uint8_t)0x40)
#define RESET_CMD ((uint8_t)0x20)
#define RESET_WDT ((uint8_t)0x02)
#define RESET_RST ((uint8_t)0x01)
#define RESET_POR ((uint8_t)0x00)
#define FILTER_EVENT_RX_SEARCH_TIMEOUT ((uint16_t)0x0001)
#define FILTER_EVENT_RX_FAIL ((uint16_t)0x0002)
#define FILTER_EVENT_TX ((uint16_t)0x0004)
#define FILTER_EVENT_TRANSFER_RX_FAILED ((uint16_t)0x0008)
#define FILTER_EVENT_TRANSFER_TX_COMPLETED ((uint16_t)0x0010)
#define FILTER_EVENT_TRANSFER_TX_FAILED ((uint16_t)0x0020)
#define FILTER_EVENT_CHANNEL_CLOSED ((uint16_t)0x0040)
#define FILTER_EVENT_RX_FAIL_GO_TO_SEARCH ((uint16_t)0x0080)
#define FILTER_EVENT_CHANNEL_COLLISION ((uint16_t)0x0100)
#define FILTER_EVENT_TRANSFER_TX_START ((uint16_t)0x0200)
#define INVALID_SDU_MASK ((uint8_t)0xFF)
#define SDU_MASK_ACK_CONFIG_BIT ((uint8_t)0x80)
#define ADV_BURST_MODE_DISABLE ((uint8_t)0x00)
#define ADV_BURST_MODE_ENABLE ((uint8_t)0x01)
#define ADV_BURST_MODES_MAX_SIZE ((uint8_t)0x03)
#define ADV_BURST_MODES_SIZE_8_BYTES ((uint8_t)0x01)
#define ADV_BURST_MODES_SIZE_16_BYTES ((uint8_t)0x02)
#define ADV_BURST_MODES_SIZE_24_BYTES ((uint8_t)0x03)
#define ADV_BURST_MODES_MASK ((uint8_t)0x03)
#define ADV_BURST_MODES_FREQ_HOP ((uint8_t)0x01)
#define ADV_BURST_MODES_RESERVED0 ((uint8_t)0x02)
#define ENCRYPTION_DISABLED_MODE ((uint8_t) 0x00)
#define ENCRYPTION_BASIC_REQUEST_MODE ((uint8_t) 0x01)
#define ENCRYPTION_USER_DATA_REQUEST_MODE ((uint8_t) 0x02)
#define MAX_SUPPORTED_ENCRYPTION_MODE ENCRYPTION_USER_DATA_REQUEST_MODE
#define ENCRYPTION_USER_DATA_SIZE ((uint8_t)19)
#define ENCRYPTION_INFO_SET_CRYPTO_ID ((uint8_t)0x00)
#define ENCRYPTION_INFO_SET_CUSTOM_USER_DATA ((uint8_t)0x01)
#define ENCRYPTION_INFO_SET_RNG_SEED ((uint8_t)0x02)
#define ENCRYPTION_INFO_GET_SUPPORTED_MODE ((uint8_t)0x00)
#define ENCRYPTION_INFO_GET_CRYPTO_ID ((uint8_t)0x01)
#define ENCRYPTION_INFO_GET_CUSTOM_USER_DATA ((uint8_t)0x02)
#define RFACTIVE_NOTIFICATION_DISABLED_MODE ((uint8_t)0x00)
#define RFACTIVE_NOTIFICATION_ONE_TIME_MODE ((uint8_t)0x01)
#define RFACTIVE_NOTIFICATION_CONTINUOUS_MODE ((uint8_t)0x02)
#define RFACTIVE_NOTIFICATION_MIN_TIME_THRESHOLD ((uint16_t)0x00A4)
#define WAKEON_RF_ACTIVITY_NONE ((uint8_t)0x00)
#define WAKEON_RF_ACTIVITY_TX ((uint8_t)0x01)
#define WAKEON_RF_ACTIVITY_RX ((uint8_t)0x02)
#define WAKEON_RF_ACTIVITY_ALL ((uint8_t)0x03)
#define ENHANCED_CHANNEL_SPACING_DISABLE ((uint8_t)0x00)
#define ENHANCED_CHANNEL_SPACING_ENABLE ((uint8_t)0x01)
#define RESPONSE_NO_ERROR ((uint8_t)0x00)
#define NO_EVENT ((uint8_t)0x00)
#define EVENT_RX_SEARCH_TIMEOUT ((uint8_t)0x01)
#define EVENT_RX_FAIL ((uint8_t)0x02)
#define EVENT_TX ((uint8_t)0x03)
#define EVENT_TRANSFER_RX_FAILED ((uint8_t)0x04)
#define EVENT_TRANSFER_TX_COMPLETED ((uint8_t)0x05)
#define EVENT_TRANSFER_TX_FAILED ((uint8_t)0x06)
#define EVENT_CHANNEL_CLOSED ((uint8_t)0x07)
#define EVENT_RX_FAIL_GO_TO_SEARCH ((uint8_t)0x08)
#define EVENT_CHANNEL_COLLISION ((uint8_t)0x09)
#define EVENT_TRANSFER_TX_START ((uint8_t)0x0A)
#define EVENT_TRANSFER_NEXT_DATA_BLOCK ((uint8_t)0x11)
#define CHANNEL_IN_WRONG_STATE ((uint8_t)0x15)
#define CHANNEL_NOT_OPENED ((uint8_t)0x16)
#define CHANNEL_ID_NOT_SET ((uint8_t)0x18)
#define CLOSE_ALL_CHANNELS ((uint8_t)0x19)
#define TRANSFER_IN_PROGRESS ((uint8_t)0x1F)
#define TRANSFER_SEQUENCE_NUMBER_ERROR ((uint8_t)0x20)
#define TRANSFER_IN_ERROR ((uint8_t)0x21)
#define TRANSFER_BUSY ((uint8_t)0x22)
#define MESSAGE_SIZE_EXCEEDS_LIMIT ((uint8_t)0x27)
#define INVALID_MESSAGE ((uint8_t)0x28)
#define INVALID_NETWORK_NUMBER ((uint8_t)0x29)
#define INVALID_LIST_ID ((uint8_t)0x30)
#define INVALID_SCAN_TX_CHANNEL ((uint8_t)0x31)
#define INVALID_PARAMETER_PROVIDED ((uint8_t)0x33)
#define EVENT_QUE_OVERFLOW ((uint8_t)0x35)
#define EVENT_ENCRYPT_NEGOTIATION_SUCCESS ((uint8_t)0x38)
#define EVENT_ENCRYPT_NEGOTIATION_FAIL ((uint8_t)0x39)
#define EVENT_RFACTIVE_NOTIFICATION ((uint8_t)0x3A)
#define EVENT_CONNECTION_START ((uint8_t)0x3B)
#define EVENT_CONNECTION_SUCCESS ((uint8_t)0x3C)
#define EVENT_CONNECTION_FAIL ((uint8_t)0x3D)
#define EVENT_CONNECTION_TIMEOUT ((uint8_t)0x3E)
#define EVENT_CONNECTION_UPDATE ((uint8_t)0x3F)
#define NO_RESPONSE_MESSAGE ((uint8_t)0x50)
#define EVENT_RX ((uint8_t)0x80)
#define EVENT_BLOCKED ((uint8_t)0xFF)
#endif
#ifndef ANTMESSAGE_H
#define ANTMESSAGE_H 
#include <stdint.h>
#define MESG_TX_SYNC ((uint8_t)0xA4)
#define MESG_RX_SYNC ((uint8_t)0xA5)
#define MESG_SYNC_SIZE ((uint8_t)1)
#define MESG_SIZE_SIZE ((uint8_t)1)
#define MESG_ID_SIZE ((uint8_t)1)
#define MESG_CHANNEL_NUM_SIZE ((uint8_t)1)
#define MESG_EXT_MESG_BF_SIZE ((uint8_t)1)
#define MESG_CHECKSUM_SIZE ((uint8_t)1)
#define MESG_DATA_SIZE ((uint8_t)9)
#define ANT_EXT_MESG_DEVICE_ID_FIELD_SIZE ((uint8_t)4)
#define ANT_EXT_MESG_RSSI_FIELD_SIZE ((uint8_t)4)
#define ANT_EXT_MESG_TIME_STAMP_FIELD_SIZE ((uint8_t)2)
#define ANT_EXT_STRING_SIZE ((uint8_t)16)
#define MESG_ANT_MAX_PAYLOAD_SIZE ANT_STANDARD_DATA_PAYLOAD_SIZE
#define MESG_MAX_EXT_DATA_SIZE (ANT_EXT_MESG_DEVICE_ID_FIELD_SIZE + ANT_EXT_MESG_RSSI_FIELD_SIZE + ANT_EXT_MESG_TIME_STAMP_FIELD_SIZE + ANT_EXT_STRING_SIZE)
#define MESG_MAX_DATA_SIZE (MESG_ANT_MAX_PAYLOAD_SIZE + MESG_EXT_MESG_BF_SIZE + MESG_MAX_EXT_DATA_SIZE)
#define MESG_MAX_SIZE_VALUE (MESG_MAX_DATA_SIZE + MESG_CHANNEL_NUM_SIZE)
#define MESG_BUFFER_SIZE (MESG_SIZE_SIZE + MESG_ID_SIZE + MESG_CHANNEL_NUM_SIZE + MESG_MAX_DATA_SIZE + MESG_CHECKSUM_SIZE)
#define MESG_FRAMED_SIZE (MESG_ID_SIZE + MESG_CHANNEL_NUM_SIZE + MESG_MAX_DATA_SIZE)
#define MESG_HEADER_SIZE (MESG_SYNC_SIZE + MESG_SIZE_SIZE + MESG_ID_SIZE)
#define MESG_FRAME_SIZE (MESG_HEADER_SIZE + MESG_CHECKSUM_SIZE)
#define MESG_MAX_SIZE (MESG_MAX_DATA_SIZE + MESG_FRAME_SIZE)
#define MESG_SIZE_OFFSET (MESG_SYNC_SIZE)
#define MESG_ID_OFFSET (MESG_SYNC_SIZE + MESG_SIZE_SIZE)
#define MESG_DATA_OFFSET (MESG_HEADER_SIZE)
#define MESG_INVALID_ID ((uint8_t)0x00)
#define MESG_EVENT_ID ((uint8_t)0x01)
#define MESG_VERSION_ID ((uint8_t)0x3E)
#define MESG_RESPONSE_EVENT_ID ((uint8_t)0x40)
#define MESG_UNASSIGN_CHANNEL_ID ((uint8_t)0x41)
#define MESG_ASSIGN_CHANNEL_ID ((uint8_t)0x42)
#define MESG_CHANNEL_MESG_PERIOD_ID ((uint8_t)0x43)
#define MESG_CHANNEL_SEARCH_TIMEOUT_ID ((uint8_t)0x44)
#define MESG_CHANNEL_RADIO_FREQ_ID ((uint8_t)0x45)
#define MESG_NETWORK_KEY_ID ((uint8_t)0x46)
#define MESG_RADIO_TX_POWER_ID ((uint8_t)0x47)
#define MESG_RADIO_CW_MODE_ID ((uint8_t)0x48)
#define MESG_SEARCH_WAVEFORM_ID ((uint8_t)0x49)
#define MESG_SYSTEM_RESET_ID ((uint8_t)0x4A)
#define MESG_OPEN_CHANNEL_ID ((uint8_t)0x4B)
#define MESG_CLOSE_CHANNEL_ID ((uint8_t)0x4C)
#define MESG_REQUEST_ID ((uint8_t)0x4D)
#define MESG_BROADCAST_DATA_ID ((uint8_t)0x4E)
#define MESG_ACKNOWLEDGED_DATA_ID ((uint8_t)0x4F)
#define MESG_BURST_DATA_ID ((uint8_t)0x50)
#define MESG_CHANNEL_ID_ID ((uint8_t)0x51)
#define MESG_CHANNEL_STATUS_ID ((uint8_t)0x52)
#define MESG_RADIO_CW_INIT_ID ((uint8_t)0x53)
#define MESG_CAPABILITIES_ID ((uint8_t)0x54)
#define MESG_ID_LIST_ADD_ID ((uint8_t)0x59)
#define MESG_ID_LIST_CONFIG_ID ((uint8_t)0x5A)
#define MESG_OPEN_RX_SCAN_ID ((uint8_t)0x5B)
#define MESG_EXT_BROADCAST_DATA_ID ((uint8_t)0x5D)
#define MESG_EXT_ACKNOWLEDGED_DATA_ID ((uint8_t)0x5E)
#define MESG_EXT_BURST_DATA_ID ((uint8_t)0x5F)
#define MESG_CHANNEL_RADIO_TX_POWER_ID ((uint8_t)0x60)
#define MESG_GET_SERIAL_NUM_ID ((uint8_t)0x61)
#define MESG_SET_LP_SEARCH_TIMEOUT_ID ((uint8_t)0x63)
#define MESG_SERIAL_NUM_SET_CHANNEL_ID_ID ((uint8_t)0x65)
#define MESG_RX_EXT_MESGS_ENABLE_ID ((uint8_t)0x66)
#define MESG_ANTLIB_CONFIG_ID ((uint8_t)0x6E)
#define MESG_STARTUP_MESG_ID ((uint8_t)0x6F)
#define MESG_AUTO_FREQ_CONFIG_ID ((uint8_t)0x70)
#define MESG_PROX_SEARCH_CONFIG_ID ((uint8_t)0x71)
#define MESG_ADV_BURST_DATA_ID ((uint8_t)0x72)
#define MESG_COEX_PRIORITY_CONFIG_ID ((uint8_t)0x73)
#define MESG_EVENT_BUFFERING_CONFIG_ID ((uint8_t)0x74)
#define MESG_SET_SEARCH_CH_PRIORITY_ID ((uint8_t)0x75)
#define MESG_CONFIG_ADV_BURST_ID ((uint8_t)0x78)
#define MESG_EVENT_FILTER_CONFIG_ID ((uint8_t)0x79)
#define MESG_SDU_CONFIG_ID ((uint8_t)0x7A)
#define MESG_SDU_SET_MASK_ID ((uint8_t)0x7B)
#define MESG_ENCRYPT_ENABLE_ID ((uint8_t)0x7D)
#define MESG_SET_ENCRYPT_KEY_ID ((uint8_t)0x7E)
#define MESG_SET_ENCRYPT_INFO_ID ((uint8_t)0x7F)
#define MESG_ACTIVE_SEARCH_SHARING_ID ((uint8_t)0x81)
#define MESG_COEX_ADV_PRIORITY_CONFIG_ID ((uint8_t)0x82)
#define MESG_RFACTIVE_NOTIFICATION_ID ((uint8_t)0x84)
#define MSG_EXT_ID_MASK ((uint8_t)0xE0)
#define MESG_EXT_ID_0 ((uint8_t)0xE0)
#define MESG_EXT_ID_1 ((uint8_t)0xE1)
#define MESG_EXT_ID_2 ((uint8_t)0xE2)
#define MESG_EXT_ID_3 ((uint8_t)0xE3)
#define MESG_EXT_ID_4 ((uint8_t)0xE4)
#define MESG_EXT_RESPONSE_ID ((uint16_t)0xE000)
#define MESG_EXT_REQUEST_ID ((uint16_t)0xE100)
#define MESG_SET_SYNC_SERIAL_BIT_RATE ((uint16_t)0xE300)
#define MESG_SET_SYNC_SERIAL_SRDY_SLEEP ((uint16_t)0xE301)
#define MESG_ANTFS_OTA_FW_UPDATE ((uint16_t)0xE400)
#define MESG_DEBUG_ID ((uint8_t)0xF0)
#define MESG_INVALID_SIZE ((uint8_t)0)
#define MESG_VERSION_SIZE ((uint8_t)13)
#define MESG_RESPONSE_EVENT_SIZE ((uint8_t)3)
#define MESG_CHANNEL_STATUS_SIZE ((uint8_t)2)
#define MESG_UNASSIGN_CHANNEL_SIZE ((uint8_t)1)
#define MESG_ASSIGN_CHANNEL_SIZE ((uint8_t)3)
#define MESG_CHANNEL_ID_SIZE ((uint8_t)5)
#define MESG_CHANNEL_MESG_PERIOD_SIZE ((uint8_t)3)
#define MESG_CHANNEL_SEARCH_TIMEOUT_SIZE ((uint8_t)2)
#define MESG_CHANNEL_RADIO_FREQ_SIZE ((uint8_t)2)
#define MESG_CHANNEL_RADIO_TX_POWER_SIZE ((uint8_t)2)
#define MESG_NETWORK_KEY_SIZE ((uint8_t)9)
#define MESG_RADIO_TX_POWER_SIZE ((uint8_t)2)
#define MESG_RADIO_CW_MODE_SIZE ((uint8_t)3)
#define MESG_RADIO_CW_INIT_SIZE ((uint8_t)1)
#define MESG_SEARCH_WAVEFORM_SIZE ((uint8_t)3)
#define MESG_SYSTEM_RESET_SIZE ((uint8_t)1)
#define MESG_OPEN_CHANNEL_SIZE ((uint8_t)1)
#define MESG_CLOSE_CHANNEL_SIZE ((uint8_t)1)
#define MESG_REQUEST_SIZE ((uint8_t)2)
#define MESG_CAPABILITIES_SIZE ((uint8_t)8)
#define MESG_ID_LIST_ADD_SIZE ((uint8_t)6)
#define MESG_ID_LIST_CONFIG_SIZE ((uint8_t)3)
#define MESG_OPEN_RX_SCAN_SIZE ((uint8_t)2)
#define MESG_EXT_CHANNEL_RADIO_FREQ_SIZE ((uint8_t)3)
#define MESG_RADIO_CONFIG_ALWAYS_SIZE ((uint8_t)2)
#define MESG_RX_EXT_MESGS_ENABLE_SIZE ((uint8_t)2)
#define MESG_SET_TX_SEARCH_ON_NEXT_SIZE ((uint8_t)2)
#define MESG_SET_LP_SEARCH_TIMEOUT_SIZE ((uint8_t)2)
#define MESG_GET_SERIAL_NUM_SIZE ((uint8_t)4)
#define MESG_ANTLIB_CONFIG_SIZE ((uint8_t)2)
#define MESG_STARTUP_MESG_SIZE ((uint8_t)1)
#define MESG_AUTO_FREQ_CONFIG_SIZE ((uint8_t)4)
#define MESG_PROX_SEARCH_CONFIG_SIZE ((uint8_t)2)
#define MESG_COEX_PRIORITY_CONFIG_REQ_SIZE ((uint8_t)9)
#define MESG_EVENT_BUFFERING_CONFIG_REQ_SIZE ((uint8_t)6)
#define MESG_CONFIG_ADV_BURST_REQ_CAPABILITIES_SIZE ((uint8_t)4)
#define MESG_CONFIG_ADV_BURST_REQ_CONFIG_SIZE ((uint8_t)10)
#define MESG_CONFIG_ENCRYPT_REQ_CAPABILITIES_SIZE ((uint8_t)2)
#define MESG_CONFIG_ENCRYPT_REQ_CONFIG_ID_SIZE ((uint8_t)5)
#define MESG_CONFIG_ENCRYPT_REQ_CONFIG_USER_DATA_SIZE ((uint8_t)20)
#define MESG_CONFIG_ENCRYPT_REQ_CURRENT_CTR ((uint8_t)17)
#define MESG_EVENT_FILTER_CONFIG_REQ_SIZE ((uint8_t)3)
#define MESG_ACTIVE_SEARCH_SHARING_REQ_SIZE ((uint8_t)2)
#define MESG_COEX_ADV_PRIORITY_CONFIG_REQ_SIZE ((uint8_t)9)
#define MESG_RFACTIVE_NOTIFICATION_SIZE ((uint8_t)4)
#define MESG_FLASH_PROTECTION_CHECK_SIZE ((uint8_t)1)
#define MESG_BIST_SIZE ((uint8_t)6)
typedef union
{
   uint8_t ucExtMesgBF;
   struct
   {
      uint8_t bExtFieldCont : 1;
      uint8_t : 1;
      uint8_t : 1;
      uint8_t : 1;
      uint8_t : 1;
      uint8_t bANTTimeStamp : 1;
      uint8_t bANTRssi : 1;
      uint8_t bANTDeviceID : 1;
   }stExtMesgBF;
} EXT_MESG_BF;
typedef union
{
   uint32_t ulForceAlign;
   uint8_t aucMessage[MESG_BUFFER_SIZE];
   struct
   {
      uint8_t ucSize;
      union
      {
         uint8_t aucFramedData[MESG_FRAMED_SIZE];
         struct
         {
            uint8_t ucMesgID;
            union
            {
               uint8_t aucMesgData[MESG_MAX_SIZE_VALUE];
               struct
               {
                  union
                  {
                     uint8_t ucChannel;
                     uint8_t ucSubID;
                  }uData0;
                  uint8_t aucPayload[ANT_STANDARD_DATA_PAYLOAD_SIZE];
                  EXT_MESG_BF sExtMesgBF;
                  uint8_t aucExtData[MESG_MAX_EXT_DATA_SIZE];
               }stMesgData;
            }uMesgData;
         }stFramedData;
      }uFramedData;
      uint8_t ucCheckSum;
   }stMessage;
} ANT_MESSAGE;
#define ANT_MESSAGE_ulForceAlign ulForceAlign
#define ANT_MESSAGE_aucMessage aucMessage
#define ANT_MESSAGE_ucSize stMessage.ucSize
#define ANT_MESSAGE_aucFramedData stMessage.uFramedData.aucFramedData
#define ANT_MESSAGE_ucMesgID stMessage.uFramedData.stFramedData.ucMesgID
#define ANT_MESSAGE_aucMesgData stMessage.uFramedData.stFramedData.uMesgData.aucMesgData
#define ANT_MESSAGE_ucChannel stMessage.uFramedData.stFramedData.uMesgData.stMesgData.uData0.ucChannel
#define ANT_MESSAGE_ucSubID stMessage.uFramedData.stFramedData.uMesgData.stMesgData.uData0.ucSubID
#define ANT_MESSAGE_aucPayload stMessage.uFramedData.stFramedData.uMesgData.stMesgData.aucPayload
#define ANT_MESSAGE_sExtMesgBF stMessage.uFramedData.stFramedData.uMesgData.stMesgData.sExtMesgBF
#define ANT_MESSAGE_ucExtMesgBF stMessage.uFramedData.stFramedData.uMesgData.stMesgData.sExtMesgBF.ucExtMesgBF
#define ANT_MESSAGE_stExtMesgBF stMessage.uFramedData.stFramedData.uMesgData.stMesgData.sExtMesgBF.stExtMesgBF
#define ANT_MESSAGE_aucExtData stMessage.uFramedData.stFramedData.uMesgData.stMesgData.aucExtData
#define ANT_MESSAGE_ucCheckSum stMessage.ucCheckSum
#endif
