#ifndef BLE_RANGES_H__
#define BLE_RANGES_H__ 
#ifdef __cplusplus
extern "C" {
#endif
#define BLE_SVC_BASE 0x60
#define BLE_SVC_LAST 0x6B
#define BLE_RESERVED_SVC_BASE 0x6C
#define BLE_RESERVED_SVC_LAST 0x6F
#define BLE_GAP_SVC_BASE 0x70
#define BLE_GAP_SVC_LAST 0x8F
#define BLE_GATTC_SVC_BASE 0x90
#define BLE_GATTC_SVC_LAST 0x9F
#define BLE_GATTS_SVC_BASE 0xA0
#define BLE_GATTS_SVC_LAST 0xAF
#define BLE_L2CAP_SVC_BASE 0xB0
#define BLE_L2CAP_SVC_LAST 0xBF
#define BLE_EVT_INVALID 0x00
#define BLE_EVT_BASE 0x01
#define BLE_EVT_LAST 0x0F
#define BLE_GAP_EVT_BASE 0x10
#define BLE_GAP_EVT_LAST 0x2F
#define BLE_GATTC_EVT_BASE 0x30
#define BLE_GATTC_EVT_LAST 0x4F
#define BLE_GATTS_EVT_BASE 0x50
#define BLE_GATTS_EVT_LAST 0x6F
#define BLE_L2CAP_EVT_BASE 0x70
#define BLE_L2CAP_EVT_LAST 0x8F
#define BLE_OPT_INVALID 0x00
#define BLE_OPT_BASE 0x01
#define BLE_OPT_LAST 0x1F
#define BLE_GAP_OPT_BASE 0x20
#define BLE_GAP_OPT_LAST 0x3F
#define BLE_GATTC_OPT_BASE 0x40
#define BLE_GATTC_OPT_LAST 0x5F
#define BLE_GATTS_OPT_BASE 0x60
#define BLE_GATTS_OPT_LAST 0x7F
#define BLE_L2CAP_OPT_BASE 0x80
#define BLE_L2CAP_OPT_LAST 0x9F
#ifdef __cplusplus
}
#endif
#endif
